# Generated by Django 5.0.6 on 2024-10-24 05:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_thread",
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "standalone_question",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_bookamarked", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "chat_thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_thread",
                        to="chatapp.chatthread",
                    ),
                ),
            ],
            options={
                "db_table": "chat_history",
            },
        ),
    ]
