# Generated by Django 5.1.4 on 2025-01-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("upgraded", "Upgraded"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
